### ISSUE TITLE
ByteToMessageDecoder uses channelReadComplete wrongly

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#1065]
ByteToMessageDecoder uses channelReadComplete wrongly, it doesn't do anything with the event at all but it should only send the event after a number of `.continue`s when we received a `channelReadComplete`.

**Comment by weissi** [comment]
Thinking about it some more, I don't think we can really make this up from `.continue`. Probably we need to add some API for the user to call to send data rather than using `context.fireChannelRead`. I mean we can't take that away from our users but we could say that either they use `context.fireChannelRead` and manage `context.fireChannelReadComplete` themselves or they use the new sort of API.

**Comment by weissi** [comment]
Don’t think we necessarily need to do something but if we do, then it’ll be in NIO 3

**Comment by Lukasa** [comment]
I actually don't think we need to do this at all: we've always allowed `channelReadComplete` to be sent after _zero_ reads, and it's forbidden to suppress it because it's used as the signal to trigger another call to `read`. So I actually think this is fine.

@weissi if you agree then I may just close this.

**Comment by weissi** [comment]
@Lukasa yes, agreed, nothing needs to be done here and everything that could be done is probably overly complex for not much benefit.
