### ISSUE TITLE
Shutting down an already closed EventLoopGroup causes calling thread to indefinitely block

### ISSUE THREAD

**Issue by drexin** [apple/swift-nio#1081]
Reproducer:

```swift
let elg = MultiThreadedEventLoopGroup(numberOfThreads: 1)

try! elg.syncShutdownGracefully()
try! elg.syncShutdownGracefully()
```

When using the async shutdown instead, the callback of the second call is never executed.

edit: This was tested against version 2.5.1

**Comment by drexin** [comment]
I think the problem is that `EventLoop.closeGently()` is called, even when the `EventLoop` is already closed. Because we are calling from outside of that event loop, it tries to dispatch the call onto the event loop, which then never gets executed, because the event loop is already closed.

**Comment by Lukasa** [comment]
That’s almost certainly exactly what’s happening. We can try to address this, but there are limits to how effective we can be I think.

**Comment by weissi** [comment]
My position here is that you shouldn't shutdown an EL(G) twice and inclined to say that hanging is okay because it's 'undefined' behaviour.

**Comment by drexin** [comment]
I agree that it shouldn't be closed twice, but if it accidentally happens, IMHO it would be much more useful to at least crash instead of leaving the thread hanging. E.g.

```swift
public final class MultiThreadedEventLoopGroup: EventLoopGroup {
    let isRunning: Atomic<Bool> = Atomic(value: true)

    // ...

    public func shutdownGracefully(queue: DispatchQueue, _ handler: @escaping (Error?) -> Void) {
        guard let self.isRunning.exchange(with: false) else {
            fatalError("`shutdownGracefully` was called twice.") // some more descriptive message
        }
        // ...
    }
}
```

Another possibility would to have a 3 valued state like

```swift
enum RunState {
    case running
    case closing
    case closed
}
```

execute the shutdown logic only when the previous value was `running`. When it was already `closing`, store the callback in an array, so it can be called when the TLG is actually closed. Or when it was already `closed`, call the callback directly.

My preferred version would be the last, but no strong opinion. I just think we should try to avoid undefined behavior.

**Comment by Lukasa** [comment]
If we did this we would _have_ to do the second one, as the first one doesn't fix the problem: you can enter the code while a shutdown is occurring, but that shutdown may also hang. If we're going to propose to change this we should change it so it always works.

Three-state enums are a pain in the ass, of course, because they have to be unsafeBitCast to be stored into atomics (or made raw representable) neither of which is great.

I'm still on the fence about doing this: I can't really think of any situation when your code should lead to this outcome.

**Comment by drexin** [comment]
@Lukasa Anything wrong with using a lock for this? It's not a hot code path and should also be uncontended.

Again, I'm not saying that this should regularly happen, but if it does, it shouldn't hang.

**Comment by ktoso** [comment]
I'd definitely want things to blow up rather than hang to be honest, not really a believer in "people should not X and know about it" even on the layer as NIO sits on... Easier to diagnose the issues if they blow up loudly rather than just hang they'd happen elsewhere than while developing. Any worries about the cost of doing this more safely?

Ofc, as users of NIO we'll definitely do our best to not cause such double shutdowns, but in general seems like a good thing to do -- good diagnostics if wrong thing is done.
