### ISSUE TITLE
adopt SwiftPM auto-discovery

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#1104]
SwiftPM now finally supports test auto-discovery on Linux: https://twitter.com/olebegemann/status/1160846803274801152 . We should adopt. Should be as easy as deleting the Ruby and doing `swift test --enable-test-discovery`

**Comment by weissi** [comment]
Unfortunately @Lukasa just reminded me that there are a few catches here:
- to retain Swift 5.0 support we'd need to make the CI run the existing Ruby script
- if we decide to do this, we should only do it once Swift 5.1 has been released.

**Comment by 3a4oT** [comment]
@weissi I tried to play with it, but I'm not sure how to be with  `-Xswiftc -warnings-as-errors`. The problem is that when I do (swift 5.1.3 image):
```swift test --enable-test-discovery -Xswiftc -warnings-as-errors```

I get something like (which is expected) :

```
/code/.build/x86_64-unknown-linux/debug/testlist.derived/NIOConcurrencyHelpersTests.swift:6:24: error: 'testAddSub()' is deprecated: deprecated because it tests deprecated functionality
        ("testAddSub", testAddSub),
```

With `LinuxMain.swift` it's not an issue because there is a hack with `protocol LinuxMainRunner { func run() }`. Maybe it worth to create a `DeprecatedFunctionalityTestSuite` and move all those tests instead of hacking.

**Comment by weissi** [comment]
Thank you @3a4oT , I filed https://bugs.swift.org/browse/SR-12008 for this.

**Comment by 3a4oT** [comment]
https://github.com/apple/swift-package-manager/pull/2513

**Comment by weissi** [comment]
Wow awesome! Thanks @3a4oT

**Comment by Lukasa** [comment]
This is done.
