### ISSUE TITLE
StackTrace or handle crashes on server

### ISSUE THREAD

**Issue by allright** [apple/swift-nio#1144]
Is anyway to get backtrace from this error caused by swift process?

trap invalid opcode ip:558ce9da5e92 sp:7f1a31f8c570 error:0 in

?

How to use coredumps with swift?
Or can we reliably print backtrace call stack on any exception?

I use:

// Helper
class Signals {
    private let signalQueue = DispatchQueue(label: "ims.signals")
    private var sources = [DispatchSourceSignal]()

    func addSignalHandler(_ code: Int32, handler: @escaping @convention(block) (Int32) -> Void) {
        let source = DispatchSource.makeSignalSource(signal: code, queue: signalQueue)
        source.setEventHandler {
            handler(code)
        }
        source.resume()
        signal(code, SIG_IGN)
        sources.append(source)
    }
}

        func errorHandler(code:Int32) {
            Log.inf(tag, "errorHandler(signal = \(code))")
            for symbol: String in Thread.callStackSymbols {
                print(symbol)
            }
            abort()
        }

// install handlers
        signals.addSignalHandler(SIGTRAP, handler: errorHandler)
        signals.addSignalHandler(SIGFPE, handler: errorHandler)
        signals.addSignalHandler(SIGSEGV, handler: errorHandler)
//        signals.addSignalHandler(4, handler: errorHandler)

 
But this code do not always print exception stack trace.

**Comment by Lukasa** [comment]
Remember that Swift does not have exceptions: it has errors, and it has crashes. In your case, this appears to be a crash.

Instead of the custom solution, you may want to try https://github.com/ianpartridge/swift-backtrace. There is also a somewhat lengthy discussion available [on the Swift forums](https://forums.swift.org/t/crash-backtraces/25021).

In future, can I please ask that you direct general help requests like these to the [Swift forums](https://forums.swift.org) instead of to the SwiftNIO bug tracker? This bug tracker is only really for issues with SwiftNIO itself, not for wider discussions on Swift server issues. You will find more people who want to help over on the forums, as the audience for this bug tracker is small. Thanks!

**Comment by allright** [comment]
Thanks A lot! Will use Swift forums
