### ISSUE TITLE
ByteBuffer should have a fast-path overload for setBytes/writeBytes that takes a CircularBuffer<UInt8>

### ISSUE THREAD

**Issue by Lukasa** [apple/swift-nio#1216]
While `CircularBuffer` is a great data type, it has an unfortunate tendency to hit the slow path in `ByteBuffer.writeBytes` and `ByteBuffer.setBytes`. This can be partly addressed by #1215, but the better solution is to add an overload for `ByteBuffer.setBytes` and `ByteBuffer.writeBytes` that takes a `CircularBuffer<UInt8>`. This can then apply the fastest implementation, which is to copy the two regions of a `CircularBuffer` as two separate `setBytes` operations.

This is a good patch for someone with some familiarity with data structures in general, but not too much SwiftNIO knowledge.

**Comment by weissi** [comment]
@richardalow will be picking this up

**Comment by richardalow** [comment]
Unfortunately the proposed solution won't work, at least with the existing implementation of `CircularBuffer`. `CircularBuffer`'s underlying storage is `ContiguousArray<Element?>` so direct copying can't be used (the underlying memory has interleaved bytes to indicate present/nil).

However, a very significant speedup can be made by allowing specialization. The current `CircularBuffer._setSlowPath` has `@inline(never)` (and `@usableFromInline`). This prevents specialization for `CircularBuffer` which leads to a very inefficient copy. From profiling, almost all the time is spent in `UnsafeMutableBufferPointer.initialize`.

One way to improve this is to speed up that initialize by implementing `_copyContents` in `CircularBuffer`. This, however, requires implementing unsafe code and only offers a small (~30% in my tests) improvement over allowing specialization of `setSlowPath`.

We can do this simply by replacing `@usableFromInline` with `@inlinable`. This means the func has both `@inline(never)` and `@inlinable`. This isn't contradictory - the compiler will never inline (we don't want the slow path inlined to make sure the fast path isn't prevented from being inlined by bloating with the slow path) but the body is available for specialization. Conceptually, these two attributes could be thought of as '`@specializable`'. Doing this improves my benchmarks by around 50x.

After implementing this, disassembling shows `CircularBuffer.Index` equality isn't inlinable and causing unnecessary retain/release. This is because the automatic `==` method isn't inlinable. Implementing this manually and making it `@inlinable` gives almost a 2x improvement.

A further 2x can be gained by forcing specialization to the common `CircularBuffer<Uint8>'. This gives an overall speedup of around 180x.

**Comment by weissi** [comment]
thanks for the awesome explanation @richardalow !

**Comment by richardalow** [comment]
I didn't mark the above PR as fixing this as strictly it doesn't, but do we want to close anyway @Lukasa?

**Comment by Lukasa** [comment]
Yup, I think this is covered. Thanks!
