### ISSUE TITLE
NIO should assert/precondition is work is execute/submit/flatSubmitted so a closed EventLoop

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#1383]
When anybody enqueues work on an EventLoop that has been shut down, currently, you'll likely just hang without any feedback. Closing an EventLoop(Group) prematurely is programmer error so we should crash.

**Comment by weissi** [comment]
similarly we should probably forbid fulfilling promises for an already shutdown EL(G).

**Comment by realdoug** [comment]
@weissi I'd like to try to knock this one out over a week or two so long as its not super time sensitive.

**Comment by weissi** [comment]
@realdoug awesome! No, it's not time sensitive at all :)

**Comment by realdoug** [comment]
Ok i'd like to come up with a set of test cases for this.  Let me know if I've missed any.


**Execute**
expected behavior: precondition failure (crash)
```
let elg = MultiThreadedEventLoopGroup(numberOfThreads: 1)
let loop = elg.next()
try! elg.syncShutdownGracefully()
loop.execute { 1 + 1 }
```

**Submit**
expected behavior: precondition failure (crash)
```
let elg = MultiThreadedEventLoopGroup(numberOfThreads: 1)
let loop = elg.next()
try! elg.syncShutdownGracefully()
loop.submit { 1 + 1 }
```

**Schedule**
expected behavior: precondition failure (crash)
```
let elg = MultiThreadedEventLoopGroup(numberOfThreads: 1)
let loop = elg.next()
try! elg.syncShutdownGracefully()
loop.scheduleTask(in: TimeAmount.seconds(2)) { 1 + 1 }
```

**Promise**
expected behavior: precondition failure (crash)
```
let elg = MultiThreadedEventLoopGroup(numberOfThreads: 1)
let loop = elg.next()
let prom = loop.makePromise(of: Bool.self)
try! elg.syncShutdownGracefully()
prom.succeed(true) // also .fail, .completeWith
```

As far as part 2, "forbid fulfilling promises on a closed el(g)".  Currently the following results in a promise failure, which i think is correct:

```
let elg = MultiThreadedEventLoopGroup(numberOfThreads: 1)
let loop = elg.next()
let sched = loop.scheduleTask(in: TimeAmount.seconds(2)) { 1 + 1 }
sched.futureResult.whenComplete { print($0) }
elg.syncshutdownGracefully()
sleep(2)
```

And according to [this](https://github.com/apple/swift-nio/blob/master/Sources/NIO/EventLoopFuture.swift#L223-L232), resolving a promise from outside the EL will already be covered by the "execute" case above.  The only remaining possibility would be if the user resolves a promise from the same thread as an EL, which I couldn't figure out a way to reproduce yet.  Is there a valid test case for that?

Sorry if this is verbose, just want to make sure i've got all bases covered!

**Comment by weissi** [comment]
@realdoug That looks awesome! Please don't apologise, what you suggest exactly matches my expectation.

**Comment by realdoug** [comment]
One more expected crash per [this comment](https://github.com/apple/swift-nio/pull/1395#discussion_r380047031)

```
let elg = MultiThreadedEventLoopGroup(numberOfThreads: 1)
let loop = elg.next()
let sched = loop.scheduleTask(in: TimeAmount.seconds(2)) {
    1 + 1
}
sched.futureResult.whenComplete { _ in
    loop.execute {
        print(“should crash”)
    }
    1 + 1
}
try! elg.syncShutdownGracefully()
```
