### ISSUE TITLE
Add a replace decoder or replace handler function

### ISSUE THREAD

**Issue by purkylin** [apple/swift-nio#1694]
To implement a custom protocol, you may have many states and each state require a decoder. I thinks it will be very convenient to replace below code:

```swift
        context.pipeline
            .removeHandler(name: decoderName)
            .and(context.pipeline.addHandler(newHandler, name: decoderName, position: .before(self)))
            .cascade(to: nil)
```

**Comment by Davidde94** [comment]
@purkylin could you expand a little on when you might want to do this?

**Comment by purkylin** [comment]
I want to implement the [socks5 protocol](https://tools.ietf.org/html/rfc1928).
Firstly, write a decoder to parse header:

	|VER | NMETHODS | METHODS  |

Secondly, write another decoder to replace previous one, which used to parse cmd

	|VER | CMD |  RSV  | ATYP | DST.ADDR | DST.PORT |

Finally, relay request.

If the proxy has auth, I should write an auth decoder.

**Comment by Lukasa** [comment]
Can I recommend not splitting those into separate channel handlers but instead having a single SOCKS handler that manages all of this? I suggest this because transforming the channel pipeline can often be a bit fraught: you need to add buffering and other things to handle the questions of how things are ordered, and where the data ends up. If it's possible to implement an entire protocol in a single handler this will often work better than needing to flip the handlers around all the time.

**Comment by purkylin** [comment]
If I use only  one decoder and one hander, I should change the decoder's state in the hander.
