### ISSUE TITLE
Compiling NIO in Release Mode throws warnings

### ISSUE THREAD

**Issue by helje5** [apple/swift-nio#178]
### Expected behavior
No warnings, clean compile.

### Actual behavior
A set of warnings, no clean compile.

```
Compile Swift Module 'NIO' (47 sources)
/Users/helge/dev/Swift/SwiftXcode/Images/SwiftNIO_XcodeImage/.build/checkouts/swift-nio.git-3108475404973543938/Sources/NIO/EventLoopFuture.swift:316:25: warning: will never be executed
            if let me = eventLoop as? SelectableEventLoop {
                        ^
/Users/helge/dev/Swift/SwiftXcode/Images/SwiftNIO_XcodeImage/.build/checkouts/swift-nio.git-3108475404973543938/Sources/NIO/EventLoopFuture.swift:315:12: note: condition always evaluates to false
        if _isDebugAssertConfiguration() {
           ^
/Users/helge/dev/Swift/SwiftXcode/Images/SwiftNIO_XcodeImage/.build/checkouts/swift-nio.git-3108475404973543938/Sources/NIO/EventLoopFuture.swift:338:64: warning: will never be executed
        if _isDebugAssertConfiguration(), let eventLoop = self.eventLoop as? SelectableEventLoop {
                                                               ^
/Users/helge/dev/Swift/SwiftXcode/Images/SwiftNIO_XcodeImage/.build/checkouts/swift-nio.git-3108475404973543938/Sources/NIO/EventLoopFuture.swift:338:12: note: condition always evaluates to false
        if _isDebugAssertConfiguration(), let eventLoop = self.eventLoop as? SelectableEventLoop {
           ^
Compile Swift Module 'NIOTLS' (3 sources)
Compile Swift Module 'NIOHTTP1' (7 sources)
Compile Swift Module 'NIOOpenSSL' (11 sources)
Compile Swift Module 'MicroExpress' (7 sources)
/Users/helge/dev/Swift/SwiftXcode/Images/SwiftNIO_XcodeImage/.build/checkouts/MicroExpress.git-6340581023861930988/Sources/MicroExpress/Express.swift:23:26: warning: 'addHTTPServerHandlers(first:)' is deprecated: Please use configureHTTPServerPipeline
        channel.pipeline.addHTTPServerHandlers().then {
                         ^
```

### Steps to reproduce

`swift build -c release`

### SwiftNIO version/commit hash

1.2.1

### Swift & OS version (output of `swift --version && uname -a`)

Apple Swift version 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)
Target: x86_64-apple-macosx10.9
Darwin ZeaPro.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jan 11 22:59:40 PST 2018; root:xnu-3789.73.8~1/RELEASE_X86_64 x86_64

**Comment by Lukasa** [comment]
Sadly, you're right. 😞 

The first four warnings are all related to our debugging code for Futures/Promises, which keeps track of where futures and promises are allocated and then performs checking on deinit. Naturally this is very slow, so we want to avoid doing it in release builds. Sadly, the Swift compiler complains about anything guarded by `_isDebugAssertConfiguration`, and there is no way to silence it.

The final warning is because you're using a deprecated function: that's easily fixed. :smile:

We've just been quietly accepting those warnings, but you're right that clean builds are better, so right now the best solution we seem to have is to write our own function that does this insane thing:

```swift
func debugOnly(_ body: () -> Void) {
    assert({ body(); return true }())
}
```

This bizarre misuse of the assert function will work. I'll push up a patch to adopt it internally.

That said, if you loathe that construction as much as I do, feel free to chime in on [this forums.swift.org post](https://forums.swift.org/t/support-debug-only-code/11037) to help make the case for a better solution.

Thanks for the report!

**Comment by Lukasa** [comment]
See #179.

**Comment by helje5** [comment]
Why can't you embed the relevant code in `#if Debug`?

**Comment by Lukasa** [comment]
Because it's not a real thing in Swift. Nothing sets that automatically, not Xcode, and not SwiftPM, so adding it in there still keeps the code out unless you remember to manually set the `#define` either in Xcode or via `-Xswiftc "-D Debug"`, which makes it not very useful.

**Comment by helje5** [comment]
Oh right, that is funny. I could have sworn `#if DEBUG` works for me. Looks like I never left Xcode ;-)
