### ISSUE TITLE
CircularBuffer: implement Collection/Sequence special customisation points to increase perf

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#1827]
Much like #1385, `CircularBuffer` should implement some more `Collection`/`Sequence` customisation points to get better performance.
Generally, this will look something like

```
public func _customTHEFUNCTION(ARGUMENTS) {
        return try self._buffer.withVeryUnsafeBytes { ptr in
            let ptr = UnsafeRawBufferPointer(start: ptr.baseAddress!.advanced(by: self._range.lowerBound), count: self._range.count))
            return ptr.THEFUNCTION(ARGUMENTS)
        }
}
```

The `Collection` customisation points we should implement are

- [x] (possibly?) [`_customIndexOfEquatableElement`](https://github.com/apple/swift/blob/3423ee107418e635182f768f3d6160a212eed846/stdlib/public/core/Collection.swift#L523) using `ptr.firstIndex(of:)`
- [x] (possibly?) [`_customLastIndexOfEquatableElement`](https://github.com/apple/swift/blob/3423ee107418e635182f768f3d6160a212eed846/stdlib/public/core/Collection.swift#L535) using `ptr.lastIndex(of:)`
- [x] (possibly?) all three variants of [`_failEarlyRangeCheck`](https://github.com/apple/swift/blob/3423ee107418e635182f768f3d6160a212eed846/stdlib/public/core/Collection.swift#L646) by just checking the `self._range`
- [x] (possibly?) [`_customContainsEquatableElement`](https://github.com/apple/swift/blob/3423ee107418e635182f768f3d6160a212eed846/stdlib/public/core/Sequence.swift#L352) using `ptr.contains()`
- [x] [`_copyToContiguousArray`](https://github.com/apple/swift/blob/3423ee107418e635182f768f3d6160a212eed846/stdlib/public/core/Sequence.swift#L358)
- [x] [`_copyContents`](https://github.com/apple/swift/blob/3423ee107418e635182f768f3d6160a212eed846/stdlib/public/core/Sequence.swift#L362)

We also don't need to implement all of those in one go, this can be done in multiple PRs.

Some notes:
- we should back the gains up by benchmarks
- this requires basically no SwiftNIO knowledge but intermediate Swift knowledge about how protocols/Collection/Sequence

**Comment by weissi** [comment]
@Lukasa I filed this one so we don't forget. Unlike ByteBufferView, I haven't done the full research which methods would give us how much gain but `_copy*` would almost certainly be able to help lots.

**Comment by stepan-ulyanin** [comment]
@Lukasa I am looking at `_customIndexOfEquatableElement`.

**Comment by simonjbeaumont** [comment]
(Potentially naive question...)

I was looking at how `_copyContents` has recently been implemented for BBV in #2039, which made use of a `ptr.initialize(from:)` and thought maybe we could do something similar here for `CircularBuffer` except, when `tailBackingIndex` > `headBackingIndex`, it is done in two parts: first `self._buffer[headBackingIndex...]`, then `self._buffer[..<tailBackingIndex]`.

However, when I looked more closely the underlying `CircularBuffer._buffer` is a `ContiguousArray<Element?>` and so IIUC, we cannot employ this trick because the `UnsafeMutableBufferPointer<Element?>` cannot be used with an `UnsafeMutableBufferPointer<Element>` nor can it be `withMemoryRebound(to:)` because of the optional enum wrapper?

What's the approach to take for implementing a faster e.g. `_copyContents` therefore?

**Comment by Lukasa** [comment]
Correct, we can't easily implement this trick because `Element?` is not guaranteed to be layout-compatible with `Element`. In some cases it will be, but attempting to detect those cases is going to be tricky.

The main advantage in implementing `_copyContents` is that we can avoid needing to lean on the compiler to transform from public indices to private backing ones: we can operate directly on the backing indices of the collection. This will improve performance somewhat, though it won't be anywhere near as fast as dropping down to `memcpy` would.

_However_, when we eventually back this by `Deque` in a future release, we _will_ be able to access a faster path.

**Comment by stepan-ulyanin** [comment]
@Lukasa on `_customIndexOfEquatableElement`:  I think one way to do this is to find the lower bound of the [`firstRange`](https://developer.apple.com/documentation/foundation/data/3139148-firstrange) of the bytes of the `element` in the collection of bytes in the `_buffer`.  Not sure if that is the right approach as it would require to import `Foundation`.

I have it implemented, just need to open PR for the benchmark first.

**Comment by Lukasa** [comment]
Yeah I don't think we should need to use `Data`, I think we can implement this directly on the backing buffer. As we only have a single element we can simply do a pair of `ptr.firstElement` checks on the backing pointer.

**Comment by stepan-ulyanin** [comment]
> 

Ok cool, thanks! Let me keep working on this one

**Comment by stepan-ulyanin** [comment]
> Yeah I don't think we should need to use `Data`, I think we can implement this directly on the backing buffer. As we only have a single element we can simply do a pair of `ptr.firstIndex(of:)` checks on the backing pointer.

Ok cool, thanks! Let me keep working on this one

**Comment by stepan-ulyanin** [comment]
@Lukasa Can't we do something like:
```swift
public func _customIndexOfEquatableElement(_ element: Element) -> Index?? where Element: Equatable {
        guard let idx = self._buffer.firstIndex(of: element)
        else { return .some(nil) }

        return .some(Index(
            backingIndex: idx,
            backingCount: self.count,
            backingIndexOfHead: self.headBackingIndex
        ))
    }
```
This constraints the `Element` to be `Equatable` though, so not sure if this is the proper way to go in the cases where we want to have a `CircularBuffer` work with an arbitrary `Element`.

I also looked into `UnsafeRawBufferPointer` but I think the element has to be `UInt8` for us to be able to call `firstIndex (of:)` on it, am I missing something?

**Comment by Lukasa** [comment]
`_customIndexOfEquatableElement` can only be called when the `Element` is equatable anyway (it's in the name), so that's fine. We don't need to use `UnsafeRawBufferPointer`, we'd want to use `UnsafeBufferPointer<Element>`. But your approach will also work well, though we should make sure not to bother searching the elements we _know_ are unset (that is, we should only search the valid range).

**Comment by stepan-ulyanin** [comment]
After some thinking with @Lukasa, I think we can't implement `[_customIndexOfEquatableElement](https://github.com/apple/swift/blob/3423ee107418e635182f768f3d6160a212eed846/stdlib/public/core/Collection.swift#L523)` customization point because there is no requirement on the `Element` of the `CircularBuffer` to be `Equatable`.

**Comment by Lukasa** [comment]
So I think that leaves `_failEarlyRangeCheck` which needs some experimentation. I have a suspicion that we may simply want to implement it as a no-op: for `CircularBuffer` (which overrides the `index(before:)` and `index(after:)` methods) we will never actually see it anyway.

**Comment by Lukasa** [comment]
SGTM.

**Comment by stepan-ulyanin** [comment]
@Lukasa I have looked into the `_failEarlyRangeCheck`, the information is a little scarce: is it automatically called when any of the public methods are called? To me it seemed that it is just a convenience method we implement to use later in the public accessors. In this case, we already check if the index is proper with `Index.isValidIndex(for:)`, so not sure we need to implement it. Am I missing something?

**Comment by Lukasa** [comment]
I think the thing we might consider doing is implementing it as a no-op (define it with no body).

**Comment by stepan-ulyanin** [comment]
@Lukasa I popped the `_failEarlyRangeCheck` methods in https://github.com/apple/swift-nio/pull/2161. Let me know how that looks.
