### ISSUE TITLE
Is there an example on how to use NIOWebSocketClient with wss:// paths?

### ISSUE THREAD

**Issue by leisurehound** [apple/swift-nio#1841]
### Expected behavior
Am trying to implement a web socket client given a server path formatted as wss://<domain>/<path> but the instructions in NIOWebSocketClient do not indicate how to utilize such an address.

### Actual behavior
The readme explains how to connect given an address/port, or path/to/unix/socket but not how to dissect a wss:// path into any of the acceptable argument patterns by the example.  Alternatively, it'd be helpful if the example would take a wss:// argument directly or provide how to create the Target struct from a wss:// formatted target.

**Comment by Lukasa** [comment]
NIOWebSocketClient cannot use such an address, because it doesn't have access to a TLS implementation. It can only handle `ws://` schemed URLs. The way you'd do that is to use `Foundation`'s `URL` type to dissect the URL into host and port combinations.

To support wss you'd need to also depend on [`swift-nio-ssl`](https://github.com/apple/swift-nio-ssl) and use that to provide TLS for `wss` URLs. Alternatively, using [Vapor's WebSocketKit](https://github.com/vapor/websocket-kit) may provide an easier interface.
