### ISSUE TITLE
Xcode 13 GM not compiling ByteBuffer-Core

### ISSUE THREAD

**Issue by Andrewangeta** [apple/swift-nio#1955]
### Expected behavior
Successful compilation

### Actual behavior
Failed compilation.

### Steps to reproduce

1. Download Xcode 13 RC
2. Try to compile

compile error: 
`Cannot convert value of type '(UnsafeMutableRawPointer) -> Void' to specified type '@convention(c) (UnsafeMutableRawPointer?) -> Void'` 
in ByteBuffer-Core.swift

### SwiftNIO version/commit hash

version 232.2

### Swift & OS version (output of `swift --version && uname -a`)
swift-driver version: 1.26.9 Apple Swift version 5.5 (swiftlang-1300.0.31.1 clang-1300.0.29.1)
Target: x86_64-apple-macosx12.0

**Comment by bdkjones** [comment]
I am also seeing this, as shown below. Xcode Version 13.0 (13A233). Is this something that can be fixed VERY quickly, or do I need to go grab a legacy version of Xcode to get apps shipped? Thanks!

![Screen Shot 2021-09-14 at 22 22 01](https://user-images.githubusercontent.com/926566/133375441-77fbfb75-8f5f-4813-9e85-b2e883963fab.png)

**Comment by Lukasa** [comment]
Thanks folks, can you please file a Feedback Assistant report and write down the number here?

**Comment by bdkjones** [comment]
Is that....useful?

No offense, but Apple almost never replies to Radars and, when they do, it's 5 years later and the reply is: "We think is no longer an issue. Please verify with the latest version of [platform] and update your issue if necessary." From the outside, Radar is a blackhole of wasted time and effort. 

Since SwiftNIO is an Apple product (I think? It's on Apple's GitHub repo, at any rate) would it not be more efficient to get the Developer Tools team via internal channels?

**Comment by Lukasa** [comment]
Yes, it’s useful.

**Comment by bdkjones** [comment]
*shrug*, okay. Here's the number: FB9626044

**Comment by Lukasa** [comment]
Much appreciated, thank you!

**Comment by Lukasa** [comment]
Also filed as https://bugs.swift.org/browse/SR-15197.

**Comment by Joannis** [comment]
Note: NIO works correctly on iOS

**Comment by jhoughjr** [comment]
> Note: NIO works correctly on iOS

not surprising. macOS just doesn't exist to apple, as can be seen by this issue.

**Comment by dweekly** [comment]
Also seeing this with XCode GM.

Notably, this causes the gRPC-Swift "hello world" experience to fail out-of-the box:

git clone https://github.com/grpc/grpc-swift && cd grpc-swift && swift run HelloWorldServer

**Comment by Joannis** [comment]
> > Note: NIO works correctly on iOS
> 
> not surprising. macOS just doesn't exist to apple, as can be seen by this issue.

While I understand the sentiment, it's quite a bold statement. Apple may not see macOS as a platform on the level of iOS, but can you really blame them? Also, the tools in which this bug appeared are a GM for good reason, it's quite difficult to see all the bugs. And the only reason we're confronted with this bug is due to an explicit definition of the function signature.

I don't think interacting with `free` in this fashion, where you want to support many platform, is a daily usecase for most people.

**Comment by Lukasa** [comment]
Ok, I think we can work around this nicely enough: see #1956.

**Comment by bdkjones** [comment]
@Lukasa that's awesome! Any chance this point release can go out today? It'll be at least a week or two before Xcode gets fixed. Thanks for the quick work!

**Comment by Lukasa** [comment]
At this stage today is probably not practical (the core devs are all UK-based and it's 9pm here, shipping a point release that late is just asking for the gods of irony to cause it to break someone's code in a fun exciting way). However, we had a pre-existing plan to ship a point release _tomorrow_ UK time, so hopefully by the time you wake up tomorrow we'll have a point release out the door.

**Comment by Lukasa** [comment]
To tie a bow on this, the fix is available in SwiftNIO version 2.32.3.

**Comment by dweekly** [comment]
Confirmed fixed for me.
