### ISSUE TITLE
Does swift-nio have support for writing UDP clients?

### ISSUE THREAD

**Issue by dirk68-fu** [apple/swift-nio#215]
It trying to figure out how to use swift-nio for connecting to an UDP port on a remote host.

This is what I have so far:

```
let group = MultiThreadedEventLoopGroup(numThreads: 1)
let bootstrap = DatagramBootstrap(group: group)
    .channelOption(ChannelOptions.socket(SocketOptionLevel(SOL_SOCKET), SO_REUSEADDR), value: 1)
    .channelInitializer { channel in
        channel.pipeline.add(handler: MyDataHandler())
    }

defer {
    try! group.syncShutdownGracefully()
}

let channel = try! bootstrap.bind(host: "10.0.0.2", port: 12345).wait()

try channel.closeFuture.wait()

print("Client closed")

```

Unfortunately the bootstrap.bind line fails with `error: bind(descriptor:ptr:bytes:) failed: Can't assign requested address (errno: 49)`

I am most probably doing it all wrong because UDP doensn't have a connection and bind seems to be for the server part, but unfortunately I could not find any documentation on how to do it right.

**Comment by Lukasa** [comment]
You want to bind a *local* address on the client side, and then send `AddressedEnvelope<ByteBuffer>` whose destination address is the server address you want to speak to.

**Comment by dirk68-fu** [comment]
Thanks, that makes sense. I will try that.

**Comment by gmosx** [comment]
If I am only interesting in writing to the destination address do I still need to bind to a local address?

**Comment by Lukasa** [comment]
Currently SwiftNIO does require that, though you can bind port 0 and address `0.0.0.0` or `::` to get the desired behaviour.

**Comment by gmosx** [comment]
OK, thanks fo the info.
It would be great to mention this in the docs!

**Comment by mron** [comment]
Lukas,
you said:
`You want to bind a local address on the client side, and then send AddressedEnvelope<ByteBuffer> whose destination address is the server address you want to speak to.`

In my test I tried:
`channel = try bootstrap.bind(host: "127.0.0.1", port: 57150).wait()`
This did not work. The Datagrams did not get though to the server. However, when I changed from localhost to the machine address:
`channel = try bootstrap.bind(host: "10.0.0.3", port: 57150).wait()`
My messages got though to the server. Why is this?

Also, what is the lifetime of a channel? Do I need to reform a channel or can I keep a reference to it and reuse it?

**Comment by Lukasa** [comment]
To your first question, you need an IP address that can reach the server. `127.0.0.1` can only be used to reach the local machine. 

To your second question, Channels have different lifecycles. For unconnected UDP channels like this one, you can reuse them indefinitely.

**Comment by mron** [comment]
Great, Thanks for the quick reply!

**Comment by nikans** [comment]
Hello, @Lukasa, I have a somewhat related question.

I have a device that creates it's own wifi network, to which my phone is connected to. Say, the device's address is `192.168.1.5`. 
On the port 12345 the device expects a command to start transmitting via UDP. I managed to send it and receive the first datagram as a response with the help of `NWConnection`. But I can't find a way to listen to the device's updates. 
`NWListener` receives no connection on 12345, and, I believe I'm doing something conceptually wrong.
I tried SwiftNIO with the exact setup @dirk68-fu had, and received an error `bind(descriptor:ptr:bytes:): Can't assign requested address (errno: 49)` when trying to bind to `192.168.1.5:12345`. 
What am I doing wrong? Or rather, how's that supposed to be done) 
Note I don't have any control over the client (the device), since it just works that way.

Much appreciated.

**Comment by Lukasa** [comment]
How does the client send the updates? To where?

**Comment by nikans** [comment]
So as I understand the docs, it sends the data continuously on `udp://{it's IP address}:12345`. It's a video stream. I managed to start it, sending a specific command to the stated address via UDP and get the first frame in response. After that, I'm supposed to somehow listen to this channel. It shouldn't be possible, right?)

**Comment by Lukasa** [comment]
That might be where it sends _from_, but cannot be where it sends _to_. What IP address does it want to send to?

**Comment by nikans** [comment]
Supposedly to `192.168.5.100` (phone), since there're only 2 devices in the network. I've tried a udp logger for ios and it looks like it receives the data (though it crashes afterwards, so I'm not 100% sure :P ).
But somehow I'm unable to subscribe to `12345` with `NWListener`...
So considering this, using `SwiftNIO` I should be able to write to `192.168.5.1:12345` and receive on `192.168.5.100:12345`. Is it possible?

**Comment by nikans** [comment]
Thank you for a little guidance — it actually sends to `59803` :/ 
Found out with some other sniffer.

**Comment by nikans** [comment]
Thanks for a little guidance. It's become c bit more clear. 
So my issue is that I need to be a client for this device (send "start" command, and then listen for the response continuously until I decide to send "stop". Looks like it cannot be done with NW library. So I'll try to explore SwiftNIO for that. Can it be done?

**Comment by Lukasa** [comment]
It should be fine to do with both libraries. Can you walk me through your expected flow?

**Comment by nikans** [comment]
Of course. 
0. Phone connects to the device's network. I figure out the gateway (the device's IP) via `NWPathMonitor`.
1. I need to send "start" command to the device's IP and a specific port (say, `192.168.5.1:12345`). For that I establish `NWConnection` and send data when ready via `connection.send(content:completion:)`. 
2. The device then starts to continuously write in the connection's port. But using NW lib I can only get the response once via `connection.receiveMessage(completion:)` and such. I could have listened with `NWListener`, but in this use case I can't, since I have to write first and then listen for responses. And even when I create a Listener on the connection's port (with `allowLocalEndpointReuse`, if it matters), nothing happens.
3. When I'm done, I need to send "stop" in this very socket.

I experimented with some Mac too alled "PacketSender" and it receives all the responses alright, after I send a "start" command. So, is this a limitation of the NW lib, or do I miss something?

Thanks!

**Comment by nikans** [comment]
So apparently I should just call `recieveMessage` again in it's callback until I need to stop :)

**Comment by Lukasa** [comment]
Yes, you want to keep calling `receiveMessage` until you receive EOF.
