### ISSUE TITLE
SwiftNIO 2.51.1 causing crashes

### ISSUE THREAD

**Issue by 0xTim** [apple/swift-nio#2420]
SwiftNIO 2.51.1 (specifically I think [this PR](https://github.com/apple/swift-nio/pull/2414) has introduced a change that is causing crashes in Vapor. These are reproducible in both [tests](https://github.com/vapor/vapor/pull/3012) and in the wild e.g. [here](https://github.com/vapor/vapor/issues/3011). It could be that Vapor's pipeline handlers are set up wrong but the introduction of a crash for a behaviour we seem to be hitting regularly seems suboptimal!

**Comment by Lukasa** [comment]
The pipeline handler isn't set up wrong, Vapor is misbehaving. But a crash here is excessive: we can just fail instead.

The scenario is described by the crash message: `NIOHTTP1/HTTPServerPipelineHandler.swift:115: Fatal error: Unexpectedly received a response in state sentCloseOutput`. Vapor is sending a HTTP `.end` message _after_ having sent `close(mode: .output)`. That's semantically meaningless: we'll never send that `.end` because the outbound side is closed.

The `close(mode: .output)` comes from your error handler. Previously, the pipeline handler just ignored these (which is why you weren't running into trouble), but that was causing Vapor to fail to clean up some Channels. The original fix resolved that issue but exposed this one, where Vapor is unaware of the state of the Channel.

In this instance, it's sufficient for us to simply error here.

**Comment by Lukasa** [comment]
Actually, we probably _shouldn't_ error: that'll just cause Vapor to loop on `close(mode: .output)` repeatedly for no good reason.

**Comment by weissi** [comment]
> SwiftNIO 2.51.1 (specifically I think [this PR](https://github.com/apple/swift-nio/pull/2414) has introduced a change that is causing crashes in Vapor. These are reproducible in both [tests](https://github.com/vapor/vapor/pull/3012) 

@Lukasa out of curiosity, shouldn't this be caught by NIO's release tooling?

**Comment by Lukasa** [comment]
Yes, it looks like the continuous error reporting isn't working.
