### ISSUE TITLE
subscript(canonicalForm:) should not split 'user-agent' on commas

### ISSUE THREAD

**Issue by tayloraswift** [apple/swift-nio#2525]
user-agent strings often contain natural commas. when using [`HTTPHeaders.subscript(canonicalForm:)`](https://github.com/apple/swift-nio/blob/2.59.0/Sources/NIOHTTP1/HTTPTypes.swift#L478), it truncates the string.

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.2.5 (KHTML
```

**Comment by Lukasa** [comment]
Unfortunately this is an unavoidable limitation of the implementation. It exempts `Set-Cookie` as the spec suggests, but otherwise is extraordinarily naive. It should really only be called when you don’t have a specialised parser for the field and when the field is canonically a list. Otherwise it just makes a best-effort attempt.

When you have out-of-band information about how a header field should be parsed, prefer the [original representation](https://github.com/apple/swift-nio/blob/3db5c4aeee8100d2db6f1eaf3864afdad5dc68fd/Sources/NIOHTTP1/HTTPTypes.swift#L429) instead, which preserves the header field as it was received on the wire.

**Comment by Lukasa** [comment]
For many fields, incidentally, a parser can be implemented using structured fields: https://github.com/apple/swift-http-structured-headers
