### ISSUE TITLE
small memory leak in SelectableEventLoop

### ISSUE THREAD

**Issue by tanner0101** [apple/swift-nio#386]
### Expected behavior

Allocated memory should grow by 0 bytes between requests.

### Actual behavior

Allocated memory grows by 96-320 bytes between requests.

### Steps to reproduce

1. clone apple/swift-nio:master
2. run `NIOHTTP1Server` in instruments (`command+i`)
3. perform the following steps:
a: boot `NIOHTTP1Server`
b: mark generation
c: `curl localhost:8888`
d: goto b

You should see memory growing between each request.

<img width="1396" alt="screen shot 2018-05-02 at 3 58 39 pm" src="https://user-images.githubusercontent.com/1342803/39546357-1f848bd0-4e22-11e8-9eb3-1c6ad014e987.png">

### If possible, minimal yet complete reproducer code (or URL to code)

NIOHTTP1Server example on master.

### SwiftNIO version/commit hash

359f35930aaf4d7a781b02d6dac161af0d486d90

### Swift & OS version (output of `swift --version && uname -a`)

```sh
swift --version && uname -a
Apple Swift version 4.1.1 (swiftlang-902.0.50 clang-902.0.37.1)
Target: x86_64-apple-darwin17.5.0
Darwin gertrude.home 17.5.0 Darwin Kernel Version 17.5.0: Tue Mar 13 20:39:15 PDT 2018; root:xnu-4570.51.1~36/RELEASE_X86_64 x86_64
```

### Saved Instruments Trace

[nio-http1-server.trace.zip](https://github.com/apple/swift-nio/files/1968703/nio-http1-server.trace.zip)

**Comment by weissi** [comment]
@tanner0101 I just had a look at this issue and it turns out it's not actually a leak: What you see if the `autoreleasepool` itself which allocates some objects for the pool. Presumably some array where it'll store the objects someone might autorelease. When you hit 'Mark Generation', NIO will be inside of the `kevent` call waiting for IO or other things to happen.
That is done with an [within an autoreleasepool](https://github.com/apple/swift-nio/blob/master/Sources/NIO/EventLoop.swift#L497-L507) because that's a place where we call out to users and they might use Foundation which might put object into the currently active autoreleasepool.

On Linux there is no autoreleasepools so our `withAutoreleasepool` function just runs the body without first creating an autoreleasepool. But on Darwin there might be serious leaks if you don't create an autoreleasepool but use code that does (eg. Foundation).

If you want, you can replace [these lines](https://github.com/apple/swift-nio/blob/master/Sources/NIO/EventLoop.swift#L267-L269) by just `return try execute` and you should see that nothing is shown as alive anymore.

**Comment by tanner0101** [comment]
Ah okay, that makes sense. I was noticing the memory climbing every so slightly between each run of `wrk` in the overall Xcode memory graph, but I guess that's due to the internal workings of auto release pool. As long as there's no leaks when auto release pool is removed (like it is on Linux) then I'm happy to close this!

**Comment by weissi** [comment]
@tanner0101 if the memory increases and does not go down, it's not what I describe here. The autoreleasepool will be popped after every tick of the event loop. So we might have a different leak somewhere.

**Comment by weissi** [comment]
the number of objects between two `wrk` runs should be pretty much equal. It can raise after the first few requests as a few lazy data structures will be initialised but after that it should remain stable

**Comment by tanner0101** [comment]
Okay I will take another look then and see if that is still happening. I will also try removing the autoreleasepool code.

**Comment by normanmaurer** [comment]
@tanner0101 also another good way to test it is to use only one EventLoop and see if you see the increase only once.

**Comment by weissi** [comment]
@tanner0101 but only remove the ARP if you're sure no-one adds anything. In other words: No one uses Foundation :). But if you're only using `NIOHTTP1Server`, there won't be any Foundation

**Comment by tanner0101** [comment]
Will do. I have definitely noticed that using JSONCoder without ARP causes insane memory leakage haha.

**Comment by weissi** [comment]
@tanner0101 yes, pretty much anything in Foundation requires an autoreleasepool to be set up and popped. But after it has been popped all the mem should be reclaimed.
The reason you saw some objects remaining is because you marked a generation between the set up and the popping of the ARP. But in a real app, the mem usage shouldn't go up.

**Comment by tanner0101** [comment]
Ahh ok that last bit makes sense now. The call to kqueue is blocking in the middle of an ARP pop causing items to be shown as still alive. Got it. 

In that case shouldn't the items from the previous generation go to zero on the next call? I guess that's where @normanmaurer's tip to use 1 event loop comes into play.

**Comment by weissi** [comment]
@tanner0101 just this:
- run `wrk -t 8 -c 256` once to 'warm up'
- go to mem graph debugger and capture screenshot
- run `wrk -t 8 -c 256` again
- go to mem graph debugger and capture screenshot

numbers are exactly equal for `NIOHTTP1Server`:

<img width="307" alt="screen shot 2018-05-08 at 7 24 27 pm" src="https://user-images.githubusercontent.com/624238/39775394-a63102f8-52f5-11e8-9ef5-e6a94800fb6a.png">
<img width="291" alt="screen shot 2018-05-08 at 7 23 43 pm" src="https://user-images.githubusercontent.com/624238/39775395-a64b1a6c-52f5-11e8-9a8d-117d88915c13.png">

**Comment by normanmaurer** [comment]
@tanner0101 @weissi can we close this one ?

**Comment by weissi** [comment]
yes for my part
