### ISSUE TITLE
EventLoops should be harder to leak.

### ISSUE THREAD

**Issue by Lukasa** [apple/swift-nio#495]
Right now, it is pretty easy to leak an `EventLoop`: just submit any work to the loop after the loop has been closed. As the `SelectableEventLoop` has no way to reject that work, that work will sit in the queue forever, holding a `Promise` which holds a `Future` which holds a reference to the event loop. Extremely not good.

This is made more troublesome because all work items in the `SelectableEventLoop` are actually `Scheduled`s, which means they create `Future` objects that hold a reference to the loop. So submitting any work after closure, even when you don't care about the result, will leak the event loop.

This is mostly not an issue in running programs, as they tend only to close their loops at the end of the process, but it's hellish in tests. While we can say that doing this is a bug, there is no easy way for a program to detect this situation: work is not rejected by the loop, and you cannot safely check for a closed loop before you submit work (and even if you could, that's a classic TOCTOU issue that would still lead to leaks, just fewer of them).

We really need a mechanism whereby the `SelectableEventLoop` can reject work once it's closed.

**Comment by FranzBusch** [comment]
Just some minor notes. Every work on the `SelectableEventLoop` is actually a `ScheduledTask` which is a `private` class and does not actually create a retain cycle as far as I can see. I think there are two problems here:

1. `SelectableEventLoop` is still accepting work after it's closed
2. `Scheduled` holding a reference to a promise which holds a future which holds the `EventLoop`

Some ideas on how to fix it. The first thing may be fixed by simply checking the lifecycle state in `scheduleTask<T>` if that is safe to do and immediately fail the task or maybe throw a new error? The second is a bit tricker. Maybe it is possible to just cancel all the remaining `Scheduled` tasks during a shutdown?
Just my idea so far, I would be happy to implement something once we get some idea how this new mechanism should look like.

**Comment by Lukasa** [comment]
I believe this was fixed in #1395.
