### ISSUE TITLE
Question: Would we support client-side NIO on iOS ? If so, we should adopt Cocoapods and Carthage

### ISSUE THREAD

**Issue by fadi-botros** [apple/swift-nio#505]
Competitors of iOS are focusing on `async` and concurrency on low number of threads. So, what about adopting Cocoapods (or at least, make a cocoapod that has only the client parts of SwiftNIO).

Also this could facilitate making IoT apps on iOS, and would augment the chances of iOS to overcome its competitors.

But this may also not mean only making cocoapod, but also we need solid ARM support

**Comment by helje5** [comment]
You are mixing more than one topic here. It is already announced that NIO will gain Network.framework support, no?
Or is this just about adding Cocoapods support?
How would any of this „facilitate making IoT apps on iOS“?

**Comment by weissi** [comment]
Correct, SwiftNIO’s Network.framework support will be available shortly.

**Comment by Lukasa** [comment]
Our Network.framework support is [now available](https://github.com/apple/swift-nio-transport-services).

**Comment by niklassaers** [comment]
The Swift NIO cocoa pods mentioned in the question, is that available anywhere or in the works?

For my own case I've made a version of [Bolt-swift](https://github.com/Neo4j-Swift/Bolt-swift/tree/develop/swift-nio) that uses NIO + SSL instead of BlueSock as client. With BlueSock I have CocoaPods support, and I'd love to keep CocoaPods support yet using NIO

**Comment by Lukasa** [comment]
We have not implemented any such support at this time. I think we'd merge a cocoapods spec though: we definitely would for NIOTransportServices.
