### ISSUE TITLE
Probable deadlock when requesting self

### ISSUE THREAD

**Issue by kirilltitov** [apple/swift-nio#518]
### Expected behavior
I develop a distributed backend application which may at some point send TCP request to self (using BlueSocket library from IBM-Kitura). I expect all requests to succeed, including loopback ones.

### Actual behavior
When application requests self using BlueSocket, it stops responding at all. It accepts new TCP connections, but does not react in any way. BlueSocket is stuck at reading from socket. However, it's not completely frozen. If there are internal timers or smth, it will go off as usual.

### Steps to reproduce
1. Clone repository https://bitbucket.org/kirilltitov/testdrive
2. Execute `swift run`
3. Execute `echo "normal" | nc 127.0.0.1 1711` and notice correct response
4. Execute `echo "deadlock" | nc 127.0.0.1 1711`, server is now hung
All further requests are also stuck.

### SwiftNIO version/commit hash
`ba077d3be8a833faeb5924b9ecf9a942bfafa690`

### Swift & OS version (output of `swift --version && uname -a`)
OS: macOS High Sierra, Mojave, Ubuntu 16.04 (docker)
Swift: `4.2 (swiftlang-1000.0.25.1 clang-1000.10.28.1)`, also `4.1`, same result

Most probably I screwed up with `ServerHandler` class, but the problem is so hilariously confusing that I don't even have a tiny clue on how to debug it. I tried literally everything.

**Comment by Lukasa** [comment]
Rule number one of SwiftNIO is that you must not block the event loop, but unfortunately your code does exactly that. The error is in [the `send` function](https://bitbucket.org/kirilltitov/testdrive/src/b1a364b16251aa976dd533267fcf7bf83e7458fc/Sources/TestDrive/main.swift?at=master&fileviewer=file-view-default#main.swift-30:38), which you [call from inside a `ChannelHandler`](https://bitbucket.org/kirilltitov/testdrive/src/b1a364b16251aa976dd533267fcf7bf83e7458fc/Sources/TestDrive/main.swift?at=master&fileviewer=file-view-default#main.swift-60) (and so from on an event loop thread).

Allow me to reproduce your `send` function below, but with my own comment annotations.

```swift
func send(payload: String, to host: String, port: Int) -> String {
    let connection: Socket = try! Socket.create(family: .inet, type: .stream, proto: .tcp)
    try! connection.connect(to: host, port: Int32(port))  // Bad: blocking connect.
    let _ = try! connection.write(from: payload)  // Bad: blocking write.
    var output = Data()
    let _ = try! connection.read(into: &output)  // Bad: blocking read
    return String(data: output, encoding: .ascii)!
}
```

Each of the lines labelled `Bad` is a blocking operation that must not be invoked from on the event loop thread. This is because these functions will not return until the operation they have requested succeeds. In the case of connect(), that does not cause you a deadlock because the kernel will accept some number of connections without the input of SwiftNIO, so that connect call will succeed in this case. Similarly, write does not cause a deadlock because you have room in the socket send buffer, so the kernel can accept the data basically immediately. The read is where you encounter problems, because that read is blocking the event loop waiting for data. However, the event loop is the entity that is responsible for *sending* the data. In practice, the event loop never even gets to read the data you sent, because your blocking call prevents us from doing so.

The simplest code change you can make to get this to work is to change your `send` function to this:

```swift
func send(payload: String, to host: String, port: Int, promise: EventLoopPromise<String>) {
    DispatchQueue("sendQueue").async {
        let connection: Socket = try! Socket.create(family: .inet, type: .stream, proto: .tcp)
        try! connection.connect(to: host, port: Int32(port))
        let _ = try! connection.write(from: payload)
        var output = Data()
        let _ = try! connection.read(into: &output)
        promise.succeed(String(data: output, encoding: .ascii)!
    }
}
```

Your calling code then needs a refactor too:

```swift
case "deadlock":
    // request self
    let p: EventLoopPromise<String> = ctx.eventLoop.newPromise()
    TestDrive.send(payload: internalURI, to: host, port: port, promise: p)
    p.futureResult.whenSuccess {
        response = "internal response: \($0)"
        print("Response is '\(response)'")
        self.send(response, to: ctx)
    }
```

With this change your code is now blocking a background thread, rather than the event loop. That frees the event loop up to process other work.

Of course, this is still not a recommended pattern, because you don't need that extra thread at all. If you want to use SwiftNIO to handle the incoming traffic, you would probably benefit from having SwiftNIO handle the outgoing traffic as well.

If you want to mix things that use BlueSocket with things that use SwiftNIO, you must always use background threads to handle the BlueSocket work, or you will at best harm the performance of your application, and at worse cause deadlock or livelock issues.

**Comment by kirilltitov** [comment]
Thank you so much for such a detailed answer! I was considering migrating from BlueSocket to NIO (minus one dependency, you know). Now I see that this is a move I should've done in the first place.

Is it ok to use same `MultiThreadedEventLoopGroup` for both server and client in the same runtime?

**Comment by Lukasa** [comment]
It's not just ok, it's often encouraged. Unless you have a particularly deep insight into your application workload, it's generally a good idea to use relatively few event loop groups.

**Comment by normanmaurer** [comment]
Yes that’s ok

**Comment by Lukasa** [comment]
There is, but you need to be careful.

`EventLoopFuture` provides a `wait()` method you can call. That will block the calling thread until the future is resolved, and then provide the result. This is synchronous.

However, as with BlueSocket, you must *never* call `wait` from on the event loop. This is because synchronous waiting always blocks the calling thread, and if that's an event loop thread then you'll once again deadlock.

**Comment by kirilltitov** [comment]
Oh, I was asking in context of NIO socket client :)

**Comment by Lukasa** [comment]
If you are in a NIO event loop, then anything that does I/O must not be a synchronous call.

**Comment by kirilltitov** [comment]
Got it working, thank you all for help! There is one thing that bothers me in code snippet, that you provided, @Lukasa. Basically, in `whenSuccess` callback we capture `self` which is `ServerHandler` instance, and it won't be deallocated until promise resolved. I don't quite get the mechanics. `whenSuccess` returns immediately, as well as whole method execution. Say, `promise` takes some time to resolve, but what happens during that time? Why doesn't it block the next request? I mean, the `ServerHandler` instance isn't released yet.
