### ISSUE TITLE
consider offering an API to attach metadata to an EventLoop

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#60]
It can be very useful for users of SwiftNIO to attach metadata to an `EventLoop`, we should consider having an API for that.

**Comment by normanmaurer** [comment]
@weissi what would be the access pattern for it ? Is it only allow to add / get / remove on the `current` EventLoop ?

**Comment by normanmaurer** [comment]
At the moment I think I am leaning to not do this and just do #61 . This way the semantics related to concurrency are clear and its always safe.

@Lukasa @weissi thoughts ? 

Also @tanner0101 wdyt ?

**Comment by tanner0101** [comment]
My use-case is that I'd like to have one service container (dependency injection container) for each event loop. This let's me design all of our services to not care about being thread safe (since any initialized service will only be used by one thread). It seems that the distinction here between being actually _attached_ to each event loop and just being attached to a particular thread isn't really a huge deal (unless I'm missing some common use-case where you want to run more than one event loop on a single thread).

If all of that sounds right, my thinking is I can just use the APIs in #61 as a hopefully speedier replacement to the current solution using foundation thread dictionary. In which case I'm fine closing this issue. 👍

**Comment by normanmaurer** [comment]
Yep this sounds right @tanner0101

**Comment by normanmaurer** [comment]
I think we close this for now as  #61 was fixed.
