### ISSUE TITLE
EmbeddedEventLoop + .submit + .wait in tests with Vapor

### ISSUE THREAD

**Issue by zdnk** [apple/swift-nio#630]
### Expected behavior
Tests to run normally.

### Actual behavior
Tests pause and wait on line where `.wait()` is called

### Steps to reproduce

1. Create a method taking `Worker` as argument and use `worker.eventLoop.submit`
2. Create test using `EmbeddedEventLoop` as `worker` and call that method with `try` and `.wait()`
3. Run test
4. Observe test never finishes and the closure passed to `.submit()` is never called

### SwiftNIO version/commit hash

1.9.5 | 5d8148c8b45dfb449276557f22120694567dd1d2

### Swift & OS version

Apple Swift version 4.2 (swiftlang-1000.11.37.1 clang-1000.11.45.1)
Target: x86_64-apple-darwin17.7.0
Darwin czsfpgspri16fad.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

**Comment by Lukasa** [comment]
Unfortunately this expected behaviour.

`EmbeddedEventLoop` does not spawn a new thread to run tasks on the event loop. Instead, it runs tasks when you call `run` or `advanceTime(by:)`. This is mostly for testing purposes, allowing you to create fully deterministic tests.

This means that `wait`, called on the same thread that created the `EmbeddedEventLoop`, will create a deadlock. This deadlock cannot be resolved without violating the thread-safety of the `EmbeddedEventLoop`. As a rule, you must not call `wait` when using `EmbeddedEventLoop`.
