### ISSUE TITLE
bring EventLoopFuture more in line with Result

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#688]
## Description
Now that [`Result`](https://github.com/apple/swift/pull/20958/files) is coming to the Swift stdlib, I feel that we should bring `EventLoopFuture`'s API more in line with result.

This is a _proposal_, if you don't agree with anything, please comment.

## Renames

- [x] rename `.then` to `.flatMap`
- [x] rename `T` to `Success`?
- [x] rename `thenIfError` to `flatMapError`

## Other Changes

- [ ] we have `mapIfError` and `Result` has `mapError` but they're different. Our `mapIfError` turns an error into a success ant `mapError` changes the error type (which we won't support I think)

## Deliberately not bringing in line

- `Failure` type. I think most of our futures can fail for so many reasons that hard-coding this to `Swift.Error` is appropriate.

**Comment by weissi** [comment]
CC @Lukasa / @normanmaurer

**Comment by Lukasa** [comment]
> rename T to Success?

I don't think I'm in favour of this. I'm all for renaming `T`, but I don't think `Success` is the right name: it only makes sense if you're defining `Failure` as well. I might be inclined to call it `Result`, ironically.

**Comment by weissi** [comment]
@Lukasa `Result` works for me to

**Comment by normanmaurer** [comment]
+1 to what @Lukasa said...

**Comment by tanner0101** [comment]
> rename .then to .flatMap

+1. Vapor 3 was calling this method `flatMap` since before NIO's release. I've been planning on migrating to using `then` so we don't have confusing duplicate methods. If NIO changes to `flatMap`, that makes my life much easier. I also think `flatMap` is easier to learn for people that are familiar with `Array.flatMap` and `Optional.flatMap`. 

> rename T to Success

I'm more used to `Result` / `Error`. But I think anything besides `T` is an improvement considering Swift's style. 

> rename thenIfError to flatMapError

Assuming this converts an error to a new future result, +1 from me.

**Comment by weissi** [comment]
`Result` would be super annoying because of the stdlib's result type, went for `Value` now.
