### ISSUE TITLE
NIO's EBADF blacklisting maybe is a bit too much

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#702]
### Expected behavior

the following program should not crash

```
import NIO

let handle: FileHandle
//let fd = open("/tmp/foo", O_RDWR | O_TRUNC | O_CREAT) // Attention: this will truncate the file if it already exists
//if fd >= 0 {
//    handle = FileHandle(descriptor: fd)
//} else {
//    fatalError("boo")
//}

let ioThreadPool = BlockingIOThreadPool(numberOfThreads: 1)
ioThreadPool.start()
defer {
    try! ioThreadPool.syncShutdownGracefully()
}
let group = MultiThreadedEventLoopGroup(numberOfThreads: 1)
defer {
    try! group.syncShutdownGracefully()
}
let io = NonBlockingFileIO(threadPool: ioThreadPool)
handle = try FileHandle(path: "/tmp/foo")
var buffer = ByteBufferAllocator().buffer(capacity: 100)
buffer.write(bytes: "asdfadsfadsfads".utf8)

try io.write(fileHandle: handle, buffer: buffer, eventLoop: group.next()).map {
    try? handle.close()
}.wait()
```

### Actual behavior

it crashes with `Assertion failed: blacklisted errno 9 Bad file descriptor in write(descriptor:pointer:size:))` because `FileHandle(path:)` opens the fd read-only.

### Steps to reproduce

run the above program

### If possible, minimal yet complete reproducer code (or URL to code)

NIO master 13th Dec 2018

**Comment by weissi** [comment]
ok, problem is obviously that we can't race-free check if that was a socket or not because EBADF usually means that the fd doesn't exist... Given that we only do this in debug mode, maybe this is okay?

**Comment by Lukasa** [comment]
Why not expose an alternative syscall wrapper that doesn’t do the EBADF policing for this use-case?

**Comment by weissi** [comment]
Good idea, yeah!

**Comment by Lukasa** [comment]
Ok, so here's a question: do we actually want this issue?

I wrote up a fix for this, but while I was running the tests I realised that this blacklisting only blows up in debug mode. Release mode programs have their assertions compiled out, which means that in release mode this will simply throw `IOError`. I think it's defensible to argue that `EBADF` should trigger crashes in debug mode, as it will make those errors obvious to developers before their programs hit production.

What do you think? If you disagree I can still bring the patch up.

**Comment by weissi** [comment]
@Lukasa I think I agree with you.

**Comment by Lukasa** [comment]
Ok, let's not do this then.

**Comment by Jman012** [comment]
Note that #1156 changes this behavior. EBADF has been promoted from an assertion to a precondition, and will crash in release mode.

**Comment by Lukasa** [comment]
I kinda think the current behaviour is fine, tbh

**Comment by Jman012** [comment]
My use case is using SwiftNIO to make an SFTP server, where the client makes open(), read(), write(), and close()-like calls individually. I think it would be nicer if when the client opened a file descriptor that was a directory, and tried writing to it thinking it was a file, to get an error response back instead of the server crashing and losing the connection.

However, the simple fix for this is to call fstat() on the opened file descriptor before potentially reading from or writing to a directory.

I think the reason for the precondition is because the EBADF is supposedly non-recoverable. I'm not entirely sure why this is the case, but I can see why this might be favored in a library that's meant more for sockets than for file/directory handling. It will mean that anyone expecting to handle EBADF as an IOError will need to guard their code more, else they received unexpected crashes.

**Comment by Lukasa** [comment]
Yeah, the EBADF protection was present for the internal use-case of SwiftNIO, which is fairly forceful about the FDs it owns being correct. The interaction with `FileHandle` is a bit rough though. As you say, in the short term this can be worked around with `fstat`, but we should have a think about whether the right choice is to make NIO's `FileHandle` run through a different code path or whether we should be pushing this use case towards Swift System.
