### ISSUE TITLE
add popFirst to CircularBuffer/MarkedCircularBuffer

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#825]
### Expected behavior
`CircularBuffer.popFirst` / `CircularBuffer.popLast` fast

### Actual behavior
`CircularBuffer.popFirst`/`popLast` dog slow as it goes through `replaceSubrange` because it inherits the default `Collection` implementation

### Proposed fix

implement it using `removeFirst`. The implementation should actually basically be

```swift
if self.isEmpty {
    return nil
} else {
    return self.removeFirst()
```

`removeFirst`/`removeLast` are already (and were always) fast.

**Comment by ivan-gulakov** [comment]
Seems like it's not slow anymore. Now (swift5.0 06.09.2019 snapshot) It inherits RangeReplaceableCollection implementation. And it's already O(1).

P.S. I've done some benchmarks.And default implementation is the fastest.

**Comment by weissi** [comment]
@ivan-gulakov I agree it's `O(1)` but the `RangeReplaceableCollection` implementation isn't as fast as it gets. Did you benchmark `popFirst` against `removeFirst`?

**Comment by ivan-gulakov** [comment]
@weissi well, thats what i've found:
<img width="612" alt="screenshot 2019-02-22 at 23 22 42" src="https://user-images.githubusercontent.com/44394533/53269075-f44d3280-36f8-11e9-9719-bd6807bc0741.png">
<img width="582" alt="screenshot 2019-02-22 at 23 22 50" src="https://user-images.githubusercontent.com/44394533/53269076-f616f600-36f8-11e9-87d3-31223948c9c2.png">
So that functions are actually doing the same thing. What i'm saying is that there is no reason to reimplement `popLast` using `removeLast`.
Also there is no usable `popFirst` implementation in `CircularBuffer` at the moment. The reason is:
<img width="539" alt="screenshot 2019-02-22 at 23 34 27" src="https://user-images.githubusercontent.com/44394533/53269616-696d3780-36fa-11e9-8699-4a6e7a99cf37.png">

**Comment by weissi** [comment]
@ivan-gulakov got it, thanks! So for `CircularBuffer` we can just implement `popFirst` and `popLast` directly. We don't want to inherit the Collection implementation, we should just provide one directly.

**Comment by weissi** [comment]
this is done by #906
