### ISSUE TITLE
go hunt overloaded functions that make NIO hard to use

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio#882]
functions like `scheduleRepeatedTask` are basically impossible to use because they're overloaded on the closure's return type. We ought to rename them and I'm sure there's similar other ones out there.

Proposal:

 - for sync stuff: `scheduleRepeatedSyncTask` or maybe just `scheduleRepeatedTask` (closure returns `Void`)
 - for async stuff: `scheduleRepeatedAsyncTask` (closure returns `ELF<Void>`)

**Comment by weissi** [comment]
CC @Lukasa / @normanmaurer good names? We really need to come up with a name here basically today, similar naming issue in #435.

**Comment by ktoso** [comment]
Sounds alright / consistent... How about `scheduleRepeatedTask` and `scheduleRepeatedAsyncTask` though?

Actually, I might be missing semantic difference perhaps? From docs and skimming the code it does not seem like returning the future causes "don't schedule next one until current has completed" right (or does it and I misread the code?)? If it did there's another layer of naming there

**Comment by weissi** [comment]
> "don't schedule next one until current has completed" right

Correct. That's quite important because otherwise you can get this nasty 'piling up of work' with timers. Say you schedule something once a second that takes two seconds to do: bad

**Comment by weissi** [comment]
@ktoso still think `scheduleRepeatedTask` and `scheduleRepeatedAsyncTask` are good?

**Comment by ktoso** [comment]
> > "don't schedule next one until current has completed" right
> 
> Correct. That's quite important because otherwise you can get this nasty 'piling up of work' with timers. Say you schedule something once a second that takes two seconds to do: bad

Ok, good. Then mini nitpick while we're at it: this should be mentioned in the swift doc of the other method. Might seem obvious once you know it does, but such guarantee is better documented rather than not-entirely-sure-i-hope-it-does which is what I felt reading / checking the API :)

--- 

To me the "sync" feels a bit off... so yeah the naming I'd propose as mentioned. The consistent rule then becoming "things that expose/flatmap/take futures and have versions with just a T" are the "async" versions. Maybe @Lukasa or @normanmaurer have a better idea.
