### ISSUE TITLE
Easier setup for an unbound UDP channel

### ISSUE THREAD

**Issue by tbartelmess** [apple/swift-nio#893]
Hi, I am working on writing UDP client that uses an "unbound" UDP socket.

I wanted to raise two issues that I ran into with the current implementation.

1. There is no way to make a truly "unbound" channel (or if there is, the documentation is lacking), the API feels unintuitive to me, the fact that it needs to call `bind,` seems wrong since I want an unbound channel.

```swift
let bootstrap = DatagramBootstrap(group: group)
    .channelInitializer { (channel) in
        // Additional Setup

}
let connectFuture = bootstrap.bind(host: "::1", port: 0)
channel = try connectFuture.wait()
```

2. `bootstrap.bind(host: "::1", port:0)` generates a `SocketAddress.v6` (or a `SocketAddress.v4`), which has the effect that it can only where the SocketAddress matches the protocol of the "bound" address.

I think an API where the `DatagramBootstrap` has a method like `unboundChannel()` or `setup()` would be more intuitive.

I am happy to start working a PR for this issue, however, as far as I can see, allowing the `DatagramChannel` to not bound to a socket, is non-trivial change(at least while I was reading through it), which is why wanted to check if I've missed anything or if this is the desired behaviour for a reason.

**Comment by Lukasa** [comment]
Hey, thanks for filing!

> There is no way to make a truly "unbound" channel (or if there is, the documentation is lacking), the API feels unintuitive to me, the fact that it needs to call bind, seems wrong since I want an unbound channel.

This wrinkle is because there is no such thing as an unbound UDP socket. The socket API is good at hiding this, but any socket on which you call `connect` without calling `bind` *implicitly* has a bind call made, to port `0`.

The effect of calling `connect` (or indeed `sendto`) on a UDP socket without calling `bind` is not to leave it unbound: instead, it is to implicitly bind an appropriate address and then use that to send the datagrams. In the case of `connect` it will also lead to kernel-level datagram filtering.

You can validate this by performing your regular usage pattern, either using `connect` or `sendto`, and then using `getsockname` or `lsof` to validate that the port is in fact bound.

> which has the effect that it can only where the SocketAddress matches the protocol of the "bound" address.

Again, the same rule applies to an unbound socket. The difference, again, occurs when you are using dual-stack sockets, in which a bound IPv6 socket may receive IPv4 packets as well. NIO will operate in this mode.

Now, we could support "unbound" (or, more accurately, "late-bound") datagram channels, but I'm not sure how useful that is. Is there a reason the bound datagram channel is not sufficient for the use-case?

**Comment by tbartelmess** [comment]
Hi,

sorry, the fact that the `DatagramBootstrap` was is used for Server and Clients threw me off. My mistake. 

The only thing that would have been nice is, if the `DatagramChannel` would have warned me about the fact that I am sending and `AddressedEnvelope` that it can't deliver due to the a mismatch in the IP Protocol version.

But - that probably belongs into a separate issue.

**Comment by Lukasa** [comment]
That one I’d expect to be covered by the write promise failing. Did it?
