### ISSUE TITLE
Add performance test reporting bot to CI

### ISSUE THREAD

**Issue by twof** [apple/swift-nio#923]
I think it would be helpful for the quality of the framework to automatically report changes in performance via CI similar to how they do on `apple/swift` currently. 

We've done something similar for Vapor https://github.com/vapor/routing/pull/70#issuecomment-476008539

What would it take to make it happen for NIO?

**Comment by Lukasa** [comment]
The biggest concern I have here is that good performance measuring is hard. In particular, it’s very sensitive to the execution environment in which it runs, which means that in your ideal world it should run on a dedicated bare-metal machine. 

For that reason, the thing it will take to get this done is time and energy spent building the infrastructure to do it.

**Comment by weissi** [comment]
Agreed (with both of you). I think it's a fact that we need to have performance measurements automatically run, otherwise we will regress. But as Cory points out, we need a dedicated bare-metal machine for that, otherwise it'll be too noisy I think.

What might be easier is a bare-metal machine that just keeps running the performance tests on master over and over again, outputting performance graphs. That's not as good as automatically having a report on every PR but at least it'd be a start and we'd start to notice when we regress.

**Comment by twof** [comment]
>What might be easier is a bare-metal machine that just keeps running the performance tests on master over and over again, outputting performance graphs. That's not as good as automatically having a report on every PR but at least it'd be a start and we'd start to notice when we regress.

Is that what they're doing for the Swift repo? I went looking for details on their setup when I was setting up perf reporting for Vapor, and I couldn't find anything.

**Comment by tomerd** [comment]
done, you can now trigger this with “test perf please", see example in https://github.com/apple/swift-nio/pull/1066
